USE [master]
GO

/****** Object:  Database [EmployeeDetailDB]    Script Date: 18/04/21 15:00:43 ******/
CREATE DATABASE [EmployeeDetailDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeDetailDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EmployeeDetailDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeeDetailDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EmployeeDetailDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeDetailDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeeDetailDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EmployeeDetailDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeeDetailDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeeDetailDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EmployeeDetailDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeeDetailDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [EmployeeDetailDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EmployeeDetailDB] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeeDetailDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeeDetailDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeeDetailDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeeDetailDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmployeeDetailDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeeDetailDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EmployeeDetailDB] SET  READ_WRITE 
GO

